server:
  port: 8500
spring:
  datasource:
    url: jdbc:p6spy:mysql://120.78.177.161:3306/mybatis-plus?useSSL=false&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.xiaorang.mybatisplusstudy.entity